### ISSUE TITLE
KeyError in /usr/local/lib/python2.7/dist-packages/oauth_tokens/base.py

### ISSUE THREAD

**Issue by ragzovskii** [ramusus/django-oauth-tokens#2]
KeyError at /usr/local/lib/python2.7/dist-packages/oauth_tokens/base.py in authorize:73:
        log.debug('Response auth location: %s' % response.headers['location']) ...

I think better way is response.headers.get('location')

**Comment by ramusus** [comment]
The application was completely rewritten. Try to upgrade to new version
