### ISSUE TITLE
NoActiveTokens exception is thrown

### ISSUE THREAD

**Issue by nachouve** [ramusus/django-oauth-tokens#6]
I have an app running nicely using django-twitter-api with django-oauth-tokens.

After some time running, a *NoActiveTokens* exception is thrown. This is the traceback

```
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/app/myapp/views/views_actions.py" in safe_update
  249.             update_user = updateUser(request,user.screen_name)
File "/app/myapp/views/views_actions.py" in updateUser
  39.     api = twitter_api.api.TwitterApi().get_api() #other resources "user,help,..." 
File "/app/.heroku/python/lib/python2.7/site-packages/twitter_api/api.py" in get_api
  26.         token = self.get_token(**kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/oauth_tokens/api.py" in get_token
  151.                     "There is no active AccessTokens for provider %s with kwargs %s" % (self.provider, kwargs))

Exception Type: NoActiveTokens at /safe_update/
Exception Value: There is no active AccessTokens for provider twitter with kwargs {}
```

After check on the DB I see there is a valid register on AccessToken:

```ipython
In [1]: from oauth_tokens.models import *
In [2]: tokens  = AccessToken.objects.all()                                                                                                                                                                                          
In [3]: print len(tokens)
Out[3] 1
In [4]: tokens[0]
Out[4]: <AccessToken: #00000000000000000-XXXXXXXXXXXXX>
In [5]: t = tokens[0] 
...
In [9]: t.provider
Out[9]: u'twitter'
In [10]: str(t.expires_at)
Out[10]: 'None'
```

After restart the webserver it works again. 

Any clues to solve this problem? Thank you!

**Comment by ramusus** [comment]
That seems to be strange for me. Try to update to latest version and debug the problem. I can not tell what the reason of absence of tokens if kwargs and self.used_access_tokens are empty. The method should return token with no filter parameters. possible there is some strange filtration..

And publish in public secret part of tokens is not recommended, I changed it for your security.

**Comment by nachouve** [comment]
Thank you very much for the response...

I'm using "django-oauth-tokens=0.4.11".

It's only happens on the server, there is no problem on my local environment. Could you give me some hints about how to debugging that on remote servers like Heroku?

**Comment by ramusus** [comment]
I updated django-oauth-tokens=0.4.12 and made exception message more verbose,
Perhaps you have used_tokens defined and queryset is empty because of this filtration.

Try to update and check exception message

**Comment by nachouve** [comment]
You are right: the token is on the used_tokens list:

```
There is no active AccessTokens for provider twitter with kwargs: {}, used_tokens: [u'00000000000000000----XXXXXXXXXXXXX']
```

If I understand correctly, *used_tokens* are only append to *used_tokens* when on *django_twitter_api* receives a 88 error code (rate limit). If the rate limit has been exceeded then It sleeps for 15 minutes (the maximum time to ensure a new interval window) and do again the call.

My code makes a bunch of calls for statuses/users each 5 minutes and also check some rate limits... So I think that is the problem... Maybe It can not release the token from used_tokens because the my calls?

**Comment by ramusus** [comment]
Yes, you are right. In your case method handle_error_no_active_tokens() is not called at all and exception is not handled

In this case I recommend to you use 
```
from twitter_api.api import api_call
api_call(...) 
```
method instead of 

```
api = twitter_api.api.TwitterApi().get_api()
```

**Comment by nachouve** [comment]
It works perfectly! Thank you very much!
